### ISSUE TITLE
The Google Drive link seems to be broken on Quick Start

### ISSUE THREAD

**Issue by sehilyi** [wangqianwen0418/DRAVA#16]
On https://qianwen.info/DRAVA/#/quick-start:

> The easiest way to run Drava on your computer is to download the [zip file from Google Drive](https://drive.google.com/file/d/10I4cf2TMXX76f33UEz6GTI9te9UQKcHR/view?usp=sharing) and run it using Python.

When I click on the link, I see the following message.

<img width="969" alt="Screen Shot 2022-08-10 at 10 15 46" src="https://user-images.githubusercontent.com/9922882/183926150-f8a7d9b0-81eb-4a14-ad6d-77f2dfcaecbc.png">

**Comment by wangqianwen0418** [comment]
Thanks for reporting this issue! It is fixed now

**Comment by wangqianwen0418** [comment]
BTW, the zip file does not include the latest changes and I will upload a updated version later
